version: '3.5'
# 新增挂载卷
volumes:
  unison-lnmp-sync:
    external: true

services:
    nginx:
#       
        volumes:
            - unison-lnmp-sync:/app:nocopy
            - ./sites/phpinfo:/phpinfo
            - ./docker/nginx/etc/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/etc/conf.d/upstream.conf:/etc/nginx/conf.d/upstream.conf
            - ./docker/nginx/etc/sites-enabled/:/etc/nginx/sites-enabled/
            - ./docker/nginx/etc/local-sites-enabled/:/etc/nginx/local-sites-enabled/  
    php:
        volumes:
            - unison-lnmp-sync:/app:nocopy
            - ./sites/phpinfo:/phpinfo
            - ./bin/composer:/usr/local/bin/composer
            - ./docker/php7-fpm/etc/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ./docker/php7-fpm/etc/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php7-fpm/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
       
